from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Iterable


class AnswerSource(str, Enum):
    USER = "user"
    POLICY = "policy"
    RESUME = "resume"
    IMPORTED = "imported"
    GENERATED = "generated"


class ResolutionStatus(str, Enum):
    RESOLVED = "resolved"
    REVIEW = "review"
    MISSING = "missing"


SENSITIVE_KEYS = frozenset({
    "work_authorization",
    "sponsorship",
    "citizenship",
    "security_clearance",
    "salary_expectation",
    "criminal_record",
    "disability",
    "veteran_status",
    "gender",
    "race_ethnicity",
})


@dataclass(frozen=True, slots=True)
class AnswerRecord:
    key: str
    value: Any
    source: AnswerSource
    confidence: float = 1.0
    note: str = ""


@dataclass(frozen=True, slots=True)
class FieldRequest:
    key: str
    required: bool = True
    sensitive: bool | None = None


@dataclass(frozen=True, slots=True)
class ResolvedAnswer:
    key: str
    status: ResolutionStatus
    value: Any = None
    source: AnswerSource | None = None
    reason: str = ""


class AnswerVault:
    """Resolve application answers while preserving provenance.

    Sensitive facts are never inferred from resume text or generated by an LLM.
    This makes the automation fail closed instead of inventing consequential
    answers to get past an application form.
    """

    def __init__(self, records: Iterable[AnswerRecord] = ()) -> None:
        self._records: dict[str, AnswerRecord] = {}
        for record in records:
            self.put(record)

    def put(self, record: AnswerRecord) -> None:
        if not 0.0 <= record.confidence <= 1.0:
            raise ValueError("confidence must be between 0 and 1")
        self._records[record.key] = record

    def resolve(self, request: FieldRequest) -> ResolvedAnswer:
        record = self._records.get(request.key)
        is_sensitive = request.sensitive if request.sensitive is not None else request.key in SENSITIVE_KEYS
        if record is None:
            return ResolvedAnswer(
                key=request.key,
                status=ResolutionStatus.MISSING if request.required else ResolutionStatus.REVIEW,
                reason="no answer stored",
            )

        if is_sensitive and record.source not in {AnswerSource.USER, AnswerSource.POLICY}:
            return ResolvedAnswer(
                key=request.key,
                status=ResolutionStatus.REVIEW,
                source=record.source,
                reason="sensitive answer requires explicit user or policy provenance",
            )

        minimum_confidence = 1.0 if is_sensitive else 0.8
        if record.confidence < minimum_confidence:
            return ResolvedAnswer(
                key=request.key,
                status=ResolutionStatus.REVIEW,
                source=record.source,
                reason=f"confidence {record.confidence:.2f} is below {minimum_confidence:.2f}",
            )

        if record.source is AnswerSource.GENERATED and request.required:
            return ResolvedAnswer(
                key=request.key,
                status=ResolutionStatus.REVIEW,
                source=record.source,
                reason="required fields cannot rely on generated facts",
            )

        return ResolvedAnswer(
            key=request.key,
            status=ResolutionStatus.RESOLVED,
            value=record.value,
            source=record.source,
            reason="answer accepted",
        )

    def resolve_many(self, requests: Iterable[FieldRequest]) -> dict[str, ResolvedAnswer]:
        return {request.key: self.resolve(request) for request in requests}
