/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Adapters */
        get: operations["adapters_api_adapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Answer */
        post: operations["save_answer_api_answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply */
        post: operations["apply_api_applications__application_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_applications__application_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description Draft a résumé and cover letter from verified profile facts (needs owner approval).
         */
        post: operations["generate_api_applications__application_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Check
         * @description Succeeds only with a valid API key (used by the app's connection test).
         */
        get: operations["auth_check_api_auth_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backups
         * @description Backup file names, sizes and times (newest first). Never the file contents.
         */
        get: operations["backups_api_backups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Discovery */
        post: operations["run_discovery_api_discovery_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flags */
        get: operations["flags_api_flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flags/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Flag
         * @description Set a known flag. Live-submission flags can only be turned off.
         */
        put: operations["update_flag_api_flags__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Open to everyone; details only for authenticated callers.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Form
         * @description Fetch the job's real application form (read-only) and plan it against the vault.
         *
         *     No state changes, no evidence, nothing submitted. Values for sensitive or
         *     legal fields are redacted in the response.
         */
        get: operations["job_form_api_jobs__job_id__form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Materials */
        get: operations["job_materials_api_jobs__job_id__materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/materials/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Job Materials
         * @description Create new DRAFT versions from verified facts. Approved versions are kept; nothing is attached or sent.
         */
        post: operations["generate_job_materials_api_jobs__job_id__materials_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kill Switch */
        get: operations["kill_switch_api_kill_switch_get"];
        put?: never;
        /**
         * Set Kill Switch
         * @description Engage (always allowed) or disengage (needs ``confirm: true``) the kill switch.
         */
        post: operations["set_kill_switch_api_kill_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Material */
        get: operations["material_api_materials__material_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Approve this draft version. Only approved versions can ever be attached to a form.
         */
        post: operations["approve_api_materials__material_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}/file/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Material File */
        get: operations["material_file_api_materials__material_id__file__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/{material_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_materials__material_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Fact */
        post: operations["create_fact_api_profile_facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Fact
         * @description Replace a fact's content. It becomes unverified unless ``verified`` is true in the same request.
         */
        put: operations["update_fact_api_profile_facts__fact_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/facts/{fact_id}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Fact */
        post: operations["delete_fact_api_profile_facts__fact_id__remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/facts/{fact_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Fact */
        post: operations["verify_fact_api_profile_facts__fact_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Profile
         * @description Import a YAML/JSON profile, or pasted résumé text (always imported UNVERIFIED).
         */
        post: operations["import_profile_api_profile_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reports Summary */
        get: operations["reports_summary_api_reports_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume-facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Resume Facts */
        put: operations["save_resume_facts_api_resume_facts_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Tasks */
        get: operations["review_tasks_api_review_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Task */
        get: operations["review_task_api_review_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-tasks/{task_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Review
         * @description Approve the job/application behind a task. Never applies or submits.
         */
        post: operations["approve_review_api_review_tasks__task_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-tasks/{task_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Review */
        post: operations["reject_review_api_review_tasks__task_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-tasks/{task_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Review
         * @description Close a task without changing the job (e.g. you handled it by hand).
         */
        post: operations["resolve_review_api_review_tasks__task_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scheduler Cycles */
        get: operations["scheduler_cycles_api_scheduler_cycles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scheduler Pause
         * @description Stop starting new scheduled cycles (a running cycle finishes).
         */
        post: operations["scheduler_pause_api_scheduler_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scheduler Resume
         * @description Allow scheduled cycles again (the kill switch, if engaged, still blocks them).
         */
        post: operations["scheduler_resume_api_scheduler_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scheduler Run
         * @description Start one cycle now in the background (same gates and caps as scheduled cycles).
         */
        post: operations["scheduler_run_api_scheduler_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scheduler Status */
        get: operations["scheduler_status_api_scheduler_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scoring/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Scoring */
        post: operations["run_scoring_api_scoring_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Remote Settings */
        get: operations["get_remote_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Remote Settings
         * @description Change the safe subset (caps, quiet hours, targeting, automation on/off).
         *
         *     Unknown keys (including ``allow_live_submission``) are rejected with 422.
         */
        patch: operations["patch_remote_settings_api_settings_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerIn */
        AnswerIn: {
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Key */
            key: string;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Scope
             * @default global
             */
            scope: string;
            /**
             * Sensitive
             * @default false
             */
            sensitive: boolean;
            /**
             * Source
             * @default user
             */
            source: string;
            /** Value */
            value: string;
        };
        /** ApplicationsSummaryOut */
        ApplicationsSummaryOut: {
            /** By Stage */
            by_stage: {
                [key: string]: number;
            };
            /** Ready To Apply */
            ready_to_apply: number;
            /** Total */
            total: number;
        };
        /** AuthCheckOut */
        AuthCheckOut: {
            /** Auth */
            auth: string;
            /** Ok */
            ok: boolean;
            /** Version */
            version: string;
        };
        /** BackupOut */
        BackupOut: {
            /** Created At */
            created_at: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** BackupStatusOut */
        BackupStatusOut: {
            /** Interval Hours */
            interval_hours: number;
            /** Last Result */
            last_result: {
                [key: string]: unknown;
            } | null;
            /** Latest At */
            latest_at: string | null;
        };
        /** BackupsOut */
        BackupsOut: {
            /** Interval Hours */
            interval_hours: number;
            /** Items */
            items: components["schemas"]["BackupOut"][];
            /** Latest At */
            latest_at: string | null;
            /** Retention */
            retention: number;
        };
        /** BlockedFieldOut */
        BlockedFieldOut: {
            /** Key */
            key: string;
            /** Label */
            label: string | null;
            /** Reason */
            reason: string | null;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Section */
            section: string | null;
        };
        /** CycleOut */
        CycleOut: {
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Reason */
            reason: string | null;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Steps */
            steps: {
                [key: string]: unknown;
            };
            /** Trigger */
            trigger: string;
        };
        /** CyclesSummaryOut */
        CyclesSummaryOut: {
            last: components["schemas"]["CycleOut"] | null;
            /** Last 24H */
            last_24h: {
                [key: string]: number;
            };
        };
        /** DecisionOut */
        DecisionOut: {
            /** Decision */
            decision: string | null;
            /** Dimensions */
            dimensions: components["schemas"]["DimensionOut"][];
            /** Matched Keywords */
            matched_keywords: string[];
            /** Review Flags */
            review_flags: string[];
            /** Vetoes */
            vetoes: string[];
        };
        /** DimensionOut */
        DimensionOut: {
            /** Evidence */
            evidence: string[];
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Weight */
            weight: number;
            /** Weighted Points */
            weighted_points: number;
        };
        /** DryRunSummaryOut */
        DryRunSummaryOut: {
            /** Completed Today */
            completed_today: number;
            /** Completed Total */
            completed_total: number;
            /** Daily Cap */
            daily_cap: number;
            /** Today */
            today: number;
        };
        /** EventOut */
        EventOut: {
            /** Created At */
            created_at: string | null;
            /** From Stage */
            from_stage: string | null;
            /** Message */
            message: string;
            /** To Stage */
            to_stage: string;
        };
        /** FactCreateIn */
        FactCreateIn: {
            /**
             * Category
             * @enum {string}
             */
            category: "contact" | "summary" | "work_authorization" | "employment" | "education" | "skill" | "certification" | "language" | "project" | "achievement";
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        };
        /** FactEditIn */
        FactEditIn: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        };
        /** FactRemovedOut */
        FactRemovedOut: {
            /** Removed */
            removed: string;
        };
        /** FactVerifyIn */
        FactVerifyIn: {
            /** Verified */
            verified: boolean;
        };
        /** FlagIn */
        FlagIn: {
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /** Enabled */
            enabled: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** FlagOut */
        FlagOut: {
            /** Enabled */
            enabled: boolean;
            /** Key */
            key: string;
            /** Note */
            note: string;
        };
        /** FormFieldOut */
        FormFieldOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Legal */
            legal: boolean;
            /** Options */
            options: number;
            /** Reason */
            reason: string;
            /** Required */
            required: boolean;
            /** Section */
            section: string;
            /** Sensitive */
            sensitive: boolean;
            /** Status */
            status: string;
            /** Type */
            type: string;
            /** Value */
            value: unknown;
        };
        /** FormPreviewOut */
        FormPreviewOut: {
            /** Blockers */
            blockers: string[];
            /** Fields */
            fields: components["schemas"]["FormFieldOut"][];
            /** Form */
            form: {
                [key: string]: unknown;
            };
            /** Ready */
            ready: boolean;
        };
        /** FormStatusOut */
        FormStatusOut: {
            /** Blocked Fields */
            blocked_fields: components["schemas"]["BlockedFieldOut"][];
            /** Blockers */
            blockers: string[];
            /** Fields Filled */
            fields_filled: number | null;
            /** Fields Required */
            fields_required: number | null;
            /** Fields Total */
            fields_total: number | null;
            /** Last Error */
            last_error: string | null;
            /** Source */
            source: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "no_application" | "not_checked" | "validated" | "unavailable" | "blocked" | "in_progress";
            /** Warnings */
            warnings: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Ai */
            ai?: {
                [key: string]: unknown;
            } | null;
            /** Allow Live Submission */
            allow_live_submission?: boolean | null;
            /** Auth */
            auth: string;
            /** Automation Enabled */
            automation_enabled?: boolean | null;
            /** Continuous Run Enabled */
            continuous_run_enabled?: boolean | null;
            /** Flags */
            flags?: {
                [key: string]: boolean;
            } | null;
            /** Live Submission Locked */
            live_submission_locked?: boolean | null;
            /** Mode */
            mode?: string | null;
            /** Ok */
            ok: boolean;
            /** Open Review Tasks */
            open_review_tasks?: number | null;
            /** Resume Loaded */
            resume_loaded?: boolean | null;
            /** Submissions Today */
            submissions_today?: number | null;
            /** Unattended Allowed */
            unattended_allowed?: boolean | null;
            /** Unattended Reason */
            unattended_reason?: string | null;
            /** Version */
            version: string;
        };
        /** HistoryDayOut */
        HistoryDayOut: {
            /** Cycles */
            cycles: number;
            /** Date */
            date: string;
            /** Discovered */
            discovered: number;
            /** Dry Runs */
            dry_runs: number;
        };
        /** JobApplicationOut */
        JobApplicationOut: {
            /** Adapter */
            adapter: string | null;
            /** Attempts */
            attempts: number;
            /** Has Cover Letter */
            has_cover_letter: boolean;
            /** Id */
            id: string;
            /** Last Error */
            last_error: string | null;
            /** Materials Ready */
            materials_ready: boolean;
            /** Maturity */
            maturity: string | null;
            /** Mode */
            mode: string;
            /** Stage */
            stage: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** JobDetailOut */
        JobDetailOut: {
            application: components["schemas"]["JobApplicationOut"] | null;
            /** Application Id */
            application_id: string | null;
            /** Application Stage */
            application_stage: string | null;
            /** Company */
            company: string;
            decision: components["schemas"]["DecisionOut"] | null;
            /** Description */
            description: string;
            /** Discovered At */
            discovered_at: string | null;
            /** Eligible */
            eligible: boolean | null;
            /** Events */
            events: components["schemas"]["EventOut"][];
            form_status: components["schemas"]["FormStatusOut"];
            /** Id */
            id: string;
            /** Liveness */
            liveness: string | null;
            /** Location */
            location: string;
            /**
             * Open Review Tasks
             * @default 0
             */
            open_review_tasks: number;
            /** Platform */
            platform: string | null;
            /** Reason */
            reason: string | null;
            /** Remote */
            remote: boolean;
            /** Review Tasks */
            review_tasks: components["schemas"]["ReviewTaskOut"][];
            /** Score */
            score: number | null;
            scores: components["schemas"]["ScoresOut"];
            /** Stage */
            stage: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** JobMaterialsOut */
        JobMaterialsOut: {
            /** Application Id */
            application_id: string | null;
            /** Approved */
            approved: {
                [key: string]: string;
            };
            /** Can Generate */
            can_generate: boolean;
            /** Generate Blockers */
            generate_blockers: string[];
            /** Items */
            items: components["schemas"]["MaterialOut"][];
            /** Job Id */
            job_id: string;
            /** Job Stage */
            job_stage: string;
            /**
             * Live Submission Locked
             * @constant
             */
            live_submission_locked: true;
            /** Llm Enabled */
            llm_enabled: boolean;
        };
        /** JobOut */
        JobOut: {
            /** Application Id */
            application_id: string | null;
            /** Application Stage */
            application_stage: string | null;
            /** Company */
            company: string;
            /** Discovered At */
            discovered_at: string | null;
            /** Eligible */
            eligible: boolean | null;
            /** Id */
            id: string;
            /** Location */
            location: string;
            /**
             * Open Review Tasks
             * @default 0
             */
            open_review_tasks: number;
            /** Platform */
            platform: string | null;
            /** Reason */
            reason: string | null;
            /** Remote */
            remote: boolean;
            /** Score */
            score: number | null;
            /** Stage */
            stage: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** JobsSummaryOut */
        JobsSummaryOut: {
            /** By Stage */
            by_stage: {
                [key: string]: number;
            };
            /** Discovered Today */
            discovered_today: number;
            /** Rejected */
            rejected: number;
            /** Scored */
            scored: number;
            /** Shortlisted */
            shortlisted: number;
            /** Total */
            total: number;
        };
        /** KillSwitchIn */
        KillSwitchIn: {
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /** Engaged */
            engaged: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** KillSwitchOut */
        KillSwitchOut: {
            /** Engaged */
            engaged: boolean;
            /** Note */
            note: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** LimitsOut */
        LimitsOut: {
            /** Cycle Max Dry Runs */
            cycle_max_dry_runs: number;
            /** Cycle Max Prepare */
            cycle_max_prepare: number;
            /** Cycle Max Score */
            cycle_max_score: number;
            /** Max Applications Per Day */
            max_applications_per_day: number;
            /** Max Dry Runs Per Day */
            max_dry_runs_per_day: number;
        };
        /** LiveSubmissionOut */
        LiveSubmissionOut: {
            /** Env Allow Live Submission */
            env_allow_live_submission: boolean;
            /**
             * Locked
             * @constant
             */
            locked: true;
            /** Reason */
            reason: string;
        };
        /** MaterialActionOut */
        MaterialActionOut: {
            /** Application Stage */
            application_stage: string;
            /** Job Stage */
            job_stage: string;
            material: components["schemas"]["MaterialOut"];
            /** Materials Ready */
            materials_ready: boolean;
            /**
             * Submitted
             * @constant
             */
            submitted: false;
        };
        /** MaterialDecisionIn */
        MaterialDecisionIn: {
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** MaterialDetailOut */
        MaterialDetailOut: {
            /** Application Id */
            application_id: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Created At */
            created_at: string | null;
            /** Decided At */
            decided_at: string | null;
            /** Decision Note */
            decision_note: string;
            /** Docx Sha256 */
            docx_sha256: string | null;
            /** Facts Used */
            facts_used: string[];
            /** Generator */
            generator: string;
            /** Guard */
            guard: {
                [key: string]: unknown;
            };
            /** Has Docx */
            has_docx: boolean;
            /** Has Pdf */
            has_pdf: boolean;
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "resume" | "cover_letter";
            /** Llm */
            llm: string;
            /** Llm Report */
            llm_report: {
                [key: string]: unknown;
            };
            /** Pdf Sha256 */
            pdf_sha256: string | null;
            /** Profile Sha256 */
            profile_sha256: string;
            /** Render Warnings */
            render_warnings: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "approved" | "rejected" | "superseded";
            /** Text */
            text: string;
            /** Version */
            version: number;
        };
        /** MaterialOut */
        MaterialOut: {
            /** Application Id */
            application_id: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Created At */
            created_at: string | null;
            /** Decided At */
            decided_at: string | null;
            /** Decision Note */
            decision_note: string;
            /** Docx Sha256 */
            docx_sha256: string | null;
            /** Generator */
            generator: string;
            /** Has Docx */
            has_docx: boolean;
            /** Has Pdf */
            has_pdf: boolean;
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "resume" | "cover_letter";
            /** Llm */
            llm: string;
            /** Pdf Sha256 */
            pdf_sha256: string | null;
            /** Profile Sha256 */
            profile_sha256: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "approved" | "rejected" | "superseded";
            /** Version */
            version: number;
        };
        /** NoteIn */
        NoteIn: {
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** ProfileFactOut */
        ProfileFactOut: {
            /** Category */
            category: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Provenance */
            provenance: string;
            /** Source */
            source: string;
            /** Updated At */
            updated_at: string | null;
            /** Verified */
            verified: boolean;
            /** Verified At */
            verified_at: string | null;
        };
        /** ProfileImportIn */
        ProfileImportIn: {
            /** Content */
            content: string;
            /**
             * Filename
             * @default
             */
            filename: string;
            /**
             * Format
             * @enum {string}
             */
            format: "yaml" | "json" | "resume_text";
        };
        /** ProfileImportOut */
        ProfileImportOut: {
            /** Created */
            created: number;
            /** Keys */
            keys: string[];
            /** Unchanged */
            unchanged: number;
            /** Unverified */
            unverified: number;
            /** Updated */
            updated: number;
            /** Verified */
            verified: number;
            /** Warnings */
            warnings: string[];
        };
        /** ProfileOut */
        ProfileOut: {
            /** Categories */
            categories: string[];
            /** Facts */
            facts: components["schemas"]["ProfileFactOut"][];
            /** Missing */
            missing: string[];
            /** Ready */
            ready: boolean;
            /** Total */
            total: number;
            /** Unverified */
            unverified: number;
            /** Verified */
            verified: number;
        };
        /** QuietHoursOut */
        QuietHoursOut: {
            /** Active */
            active: boolean;
            /** End */
            end: string;
            /** Start */
            start: string;
            /** Timezone */
            timezone: string;
        };
        /** ResumeFactsIn */
        ResumeFactsIn: {
            /** Text */
            text: string;
        };
        /** ReviewActionOut */
        ReviewActionOut: {
            /** Action */
            action: string;
            /** Application Stage */
            application_stage: string | null;
            /** Job Stage */
            job_stage: string | null;
            /**
             * Live Submission Locked
             * @constant
             */
            live_submission_locked: true;
            /**
             * Submitted
             * @constant
             */
            submitted: false;
            task: components["schemas"]["ReviewTaskOut"];
        };
        /** ReviewApplicationOut */
        ReviewApplicationOut: {
            /** Adapter */
            adapter: string | null;
            /** Attempts */
            attempts: number;
            /** Has Materials */
            has_materials: boolean;
            /** Id */
            id: string;
            /** Last Error */
            last_error: string | null;
            /** Maturity */
            maturity: string | null;
            /** Mode */
            mode: string;
            /** Stage */
            stage: string;
        };
        /** ReviewJobOut */
        ReviewJobOut: {
            /** Company */
            company: string;
            /** Id */
            id: string;
            /** Location */
            location: string;
            /** Platform */
            platform: string | null;
            /** Score */
            score: number | null;
            /** Stage */
            stage: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** ReviewResolveIn */
        ReviewResolveIn: {
            /**
             * Resolution
             * @default resolved
             * @enum {string}
             */
            resolution: "resolved" | "dismissed";
        };
        /** ReviewSummaryOut */
        ReviewSummaryOut: {
            /** Closed Total */
            closed_total: number;
            /** Open */
            open: number;
            /** Open By Reason */
            open_by_reason: {
                [key: string]: number;
            };
        };
        /** ReviewTaskDetailOut */
        ReviewTaskDetailOut: {
            /** Actions */
            actions: ("approve" | "reject" | "resolve")[];
            application: components["schemas"]["ReviewApplicationOut"] | null;
            /** Application Id */
            application_id: string | null;
            /** Approve Effect */
            approve_effect: string | null;
            /** Blocked Fields */
            blocked_fields: components["schemas"]["BlockedFieldOut"][];
            /** Company */
            company: string | null;
            /** Created At */
            created_at: string | null;
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            job: components["schemas"]["ReviewJobOut"] | null;
            /** Job Id */
            job_id: string | null;
            /** Job Title */
            job_title: string | null;
            /**
             * Live Submission Locked
             * @constant
             */
            live_submission_locked: true;
            /** Materials */
            materials: components["schemas"]["MaterialOut"][];
            /** Reason Code */
            reason_code: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
        };
        /** ReviewTaskOut */
        ReviewTaskOut: {
            /** Application Id */
            application_id: string | null;
            /** Company */
            company: string | null;
            /** Created At */
            created_at: string | null;
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            /** Job Id */
            job_id: string | null;
            /** Job Title */
            job_title: string | null;
            /** Reason Code */
            reason_code: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Url */
            url: string | null;
        };
        /** RunCycleOut */
        RunCycleOut: {
            /** Reason */
            reason: string | null;
            /** Started */
            started: boolean;
            /** Status Url */
            status_url: string | null;
        };
        /** SchedulerStatusOut */
        SchedulerStatusOut: {
            /** Automation Enabled */
            automation_enabled: boolean;
            backup: components["schemas"]["BackupStatusOut"];
            /** Continuous Run Enabled */
            continuous_run_enabled: boolean;
            /** Current Cycle Id */
            current_cycle_id: string | null;
            /** Cycle In Progress */
            cycle_in_progress: boolean;
            /** Interval Minutes */
            interval_minutes: number;
            /** Kill Switch */
            kill_switch: boolean;
            last_cycle: components["schemas"]["CycleOut"] | null;
            limits: components["schemas"]["LimitsOut"];
            /** Live Submission */
            live_submission: string;
            /** Next Run At */
            next_run_at: string | null;
            /** Paused */
            paused: boolean;
            quiet_hours: components["schemas"]["QuietHoursOut"];
            /** Scheduler Thread Alive */
            scheduler_thread_alive: boolean;
            today: components["schemas"]["TodayOut"];
        };
        /** ScoresOut */
        ScoresOut: {
            /** Ai */
            ai: number | null;
            /** Deterministic */
            deterministic: number | null;
            /** Final */
            final: number | null;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Application Mode */
            application_mode: string;
            /** Auth Mode */
            auth_mode: string;
            /** Automation Enabled */
            automation_enabled: boolean;
            /** Backup Interval Hours */
            backup_interval_hours: number;
            /** Backup Retention */
            backup_retention: number;
            /** Blacklisted Companies */
            blacklisted_companies: string[];
            /** Continuous Run Enabled */
            continuous_run_enabled: boolean;
            /** Cycle Interval Minutes */
            cycle_interval_minutes: number;
            /** Cycle Max Dry Runs */
            cycle_max_dry_runs: number;
            /** Cycle Max Prepare */
            cycle_max_prepare: number;
            /** Cycle Max Score */
            cycle_max_score: number;
            /** Editable */
            editable: string[];
            /** Excluded Locations */
            excluded_locations: string[];
            /** Excluded Titles */
            excluded_titles: string[];
            /** Greenhouse Browser Verify */
            greenhouse_browser_verify: boolean;
            live_submission: components["schemas"]["LiveSubmissionOut"];
            /** Llm Fast Model */
            llm_fast_model: string;
            /** Llm Provider */
            llm_provider: string;
            /** Llm Quality Model */
            llm_quality_model: string;
            /** Max Applications Per Day */
            max_applications_per_day: number;
            /** Max Dry Runs Per Day */
            max_dry_runs_per_day: number;
            /** Min Match Score */
            min_match_score: number;
            /** Overridden */
            overridden: string[];
            /** Quiet Hours End */
            quiet_hours_end: string;
            /** Quiet Hours Start */
            quiet_hours_start: string;
            sources: components["schemas"]["SourcesOut"];
            /** Target Keywords */
            target_keywords: string[];
            /** Target Locations */
            target_locations: string[];
            /** Timezone */
            timezone: string;
        };
        /**
         * SettingsPatch
         * @description The only settings the API may change. Anything else is a 422.
         */
        SettingsPatch: {
            /** Automation Enabled */
            automation_enabled?: boolean | null;
            /** Blacklisted Companies */
            blacklisted_companies?: string[] | null;
            /** Cycle Interval Minutes */
            cycle_interval_minutes?: number | null;
            /** Cycle Max Dry Runs */
            cycle_max_dry_runs?: number | null;
            /** Cycle Max Prepare */
            cycle_max_prepare?: number | null;
            /** Cycle Max Score */
            cycle_max_score?: number | null;
            /** Excluded Locations */
            excluded_locations?: string[] | null;
            /** Excluded Titles */
            excluded_titles?: string[] | null;
            /** Max Applications Per Day */
            max_applications_per_day?: number | null;
            /** Max Dry Runs Per Day */
            max_dry_runs_per_day?: number | null;
            /** Min Match Score */
            min_match_score?: number | null;
            /** Quiet Hours End */
            quiet_hours_end?: string | null;
            /** Quiet Hours Start */
            quiet_hours_start?: string | null;
            /** Target Keywords */
            target_keywords?: string[] | null;
            /** Target Locations */
            target_locations?: string[] | null;
        };
        /** SourcesOut */
        SourcesOut: {
            /** Generic Feeds */
            generic_feeds: number;
            /** Greenhouse Boards */
            greenhouse_boards: number;
            /** Lever Companies */
            lever_companies: number;
        };
        /** SubmissionSummaryOut */
        SubmissionSummaryOut: {
            /** Daily Cap */
            daily_cap: number;
            /** Today */
            today: number;
            /** Total */
            total: number;
        };
        /** SummaryOut */
        SummaryOut: {
            applications: components["schemas"]["ApplicationsSummaryOut"];
            cycles: components["schemas"]["CyclesSummaryOut"];
            dry_runs: components["schemas"]["DryRunSummaryOut"];
            /** Generated At */
            generated_at: string;
            /** History */
            history: components["schemas"]["HistoryDayOut"][];
            jobs: components["schemas"]["JobsSummaryOut"];
            /**
             * Live Submission Locked
             * @constant
             */
            live_submission_locked: true;
            review: components["schemas"]["ReviewSummaryOut"];
            submissions: components["schemas"]["SubmissionSummaryOut"];
            /** Timezone */
            timezone: string;
        };
        /** TodayOut */
        TodayOut: {
            /** Dry Runs */
            dry_runs: number;
            /** Submissions */
            submissions: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    adapters_api_adapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    save_answer_api_answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    apply_api_applications__application_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_applications__application_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_applications__application_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_check_api_auth_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthCheckOut"];
                };
            };
        };
    };
    backups_api_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupsOut"];
                };
            };
        };
    };
    run_discovery_api_discovery_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    events_api_events__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flags_api_flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    update_flag_api_flags__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    jobs_api_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                stage?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_form_api_jobs__job_id__form_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_materials_api_jobs__job_id__materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobMaterialsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_job_materials_api_jobs__job_id__materials_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobMaterialsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_switch_api_kill_switch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchOut"];
                };
            };
        };
    };
    set_kill_switch_api_kill_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillSwitchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    material_api_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_materials__material_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MaterialDecisionIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    material_file_api_materials__material_id__file__fmt__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
                fmt: "pdf" | "docx";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_materials__material_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MaterialDecisionIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    create_fact_api_profile_facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileFactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fact_api_profile_facts__fact_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactEditIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileFactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fact_api_profile_facts__fact_id__remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRemovedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_fact_api_profile_facts__fact_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactVerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileFactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_profile_api_profile_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileImportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reports_summary_api_reports_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
        };
    };
    save_resume_facts_api_resume_facts_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeFactsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_tasks_api_review_tasks_get: {
        parameters: {
            query?: {
                status?: "open" | "closed" | "all";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_task_api_review_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_review_api_review_tasks__task_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_review_api_review_tasks__task_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_review_api_review_tasks__task_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewResolveIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scheduler_cycles_api_scheduler_cycles_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scheduler_pause_api_scheduler_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NoteIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scheduler_resume_api_scheduler_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NoteIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scheduler_run_api_scheduler_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCycleOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCycleOut"];
                };
            };
        };
    };
    scheduler_status_api_scheduler_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerStatusOut"];
                };
            };
        };
    };
    run_scoring_api_scoring_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    get_remote_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    patch_remote_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
